
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: stock_forge_development

test:
  <<: *default
  database: stock_forge_test

production:
  primary: &primary_production
    <<: *default
    database: stock_forge_production
    username: stock_forge
    password: <%= ENV["STOCK_FORGE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: stock_forge_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: stock_forge_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: stock_forge_production_cable
    migrations_paths: db/cable_migrate
